services:
  bat-app:
    image: bat-app
    container_name: bat-app
    ports:
      - "8000:8000"
    environment:
      - SMTP_LOGIN=
      - SMTP_PASSWORD=
      - SMTP_EMAIL=
      - SMTP_SERVER=
      - SMTP_PORT=
      - SECRET_KEY=                        # openssl rand -hex 32
      - ALGORITHM=HS256                    # keep unless decided otherwise
      - ACCESS_TOKEN_EXPIRE_MINUTES=30     # good value to use
      - DEFAULT_USER=
      - DEFAULT_EMAIL=
      - DEFAULT_PASSWORD=
      - CF_TURNSTILE_SITE_KEY=
      - CF_TURNSTILE_SECRET_KEY=
      # Uncomment if you will run instance behind https reverse proxy
      # - FORCE_HTTPS_PATHS=True
    volumes:
      - ./data:/bat-app/app/data:Z
